In [2]:
import numpy as np
array=np.random.random((3,2))
print(array)


[[0.50956487 0.47054584]
 [0.16152841 0.05995099]
 [0.46643357 0.47059706]]


In [3]:
import numpy as np
value=np.random.random()
print(value)

0.3603015155659327


In [5]:
import numpy as np
array=np.random.randint(2,10,size=(2,4))
print(array)

[[2 2 3 8]
 [2 9 8 5]]


In [8]:
array=np.zeros(5)
print(array)


[0. 0. 0. 0. 0.]


In [10]:
array=np.full(5, 2)
print(array)


[2 2 2 2 2]


In [13]:
array=np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
'''
Question 1

Write a Python program to convert an array to an ordinary list with the same items.
We can use the np.tolist() function.
'''
import numpy as np

def convert(arr):
    x=arr.tolist()#or x=list(arr)
    return x
arr=np.array([1,2,3,4])
convert(arr)

[1, 2, 3, 4]

In [22]:
'''
Question 2 

Write a NumPy program to compute the sum of the diagonal elements of a given array.
Hint: There are two possible methods to solve this problem: 
Manually (without direct function). 
Using the trace function
'''
import numpy as np
#we use trace() 
def sum_diag(arr):
    x=arr.trace()
    return x
arr=np.array([[1,3,5],[3,6,7]])#6+1
sum_diag(arr)

7

In [2]:
'''
Question 3

Given an array of your choice, get all the values higher than X:
If a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 
'''
def higher(arr,x):
    result = list(filter(lambda val: val > x, [val for sublist in a for val in sublist]))
    return result

a = [[1, 2], [3, 5]]
x =int(input("write a number"))
higher(a,x)




write a number3


[5]

In [3]:
'''
Question 4

Given two arrays, A & B have the same shape. 
The task is to apply addition by hand: C is the new array. 
'''
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.add(A, B)#or c=a+b
print(C)
'''
methode 2
C = np.zeros(A.shape)
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        C[i][j] = A[i][j] + B[i][j]
'''


[[ 6  8]
 [10 12]]


In [8]:
'''
Question 5

Write a NumPy program to subtract the mean of each row of a given matrix.
Hint: use the mean function
'''
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1)#si axis=0 calcule each column

# Subtract the mean of each row from the original matrix
result = matrix - row_means[:, np.newaxis]

print(result)
print(row_means[:, np.newaxis])


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
[[2.]
 [5.]
 [8.]]
